apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true" 
  name: gp3
allowVolumeExpansion: true
parameters:
  type: gp3
  fsType: ext4
  encrypted: "true"  
provisioner: ebs.csi.aws.com
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer